name: learn-github-actions
on: [push]

jobs:
  create-text-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create example.txt
        run: |
          echo "This is a test file." > example.txt
          echo "GitHub Actions created this file." >> example.txt
