name: Manual Hello Workflow

on:
  workflow_dispatch:  # UIから手動実行

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello! This workflow was triggered manually."
